[package]
name = "objs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
simple_logger = "4.1.0"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.95"
config = "0.14.0"